### ISSUE TITLE
Core JS

### ISSUE THREAD

**Issue by smowden** [grigio/meteor-babel#1]
Hey,
can you please include core.js? https://github.com/zloirock/core-js
You've included regenerator which is nice because now this package allows for generators, but you left out corejs for some reason.

**Comment by grigio** [comment]
it's included via npm https://github.com/grigio/meteor-babel/blob/master/package.js#L17

**Comment by smowden** [comment]
which means its only available on the server, can you include it in the lib folder so that its also available on the client?

**Comment by grigio** [comment]
Why should it be included also in the client? The ES6 to ES5 conversion isn't done at runtime and you shouldn't need it there

**Comment by smowden** [comment]
it has nothing to do with the transpilation process, core js is a collection of polyfills ie they are not transpiled but provided via core.js. the transpiler does not include polyfills for things like Array.from and all the other new js features.

**Comment by grigio** [comment]
Now core-js is on both and here are the tested features https://github.com/grigio/meteor-babel/blob/master/tests/basic_test.es6.js

**Comment by smowden** [comment]
thank you!
