### ISSUE TITLE
Incompatibility with reacts:react

### ISSUE THREAD

**Issue by realtaraharris** [grigio/meteor-babel#10]
Hey, it looks like meteor-babel is incompatible with reactjs:react@0.2.0.

This is what I get when I try adding it to my project:

```
=> Errors prevented startup:                  

   While building the application:
   error: conflict: two packages included in the app, reactjs:react and grigio:babel, are both
   trying to handle .jsx

=> Your application has errors. Waiting for file change.
```

**Comment by grigio** [comment]
Thanks for the report.
@benjamn how Meteor should compile JSX via `react-tools` or `babel` ?

**Comment by grigio** [comment]
@maxharris9 meteor-babel 0.0.11 doesn't manage anymore `.jsx` so you shouldn't have this issue anymore. Let me know if it fixes

**Comment by ghost** [comment]
Yes, this works! Thanks!

**Comment by tomitrescak** [comment]
Ugh, that's a shame ... I guess there was no other way, but jsx is standard for es6 files. ReactJS only stold it ...

**Comment by grigio** [comment]
http://facebook.github.io/jsx/

@tomitrescak jsx isn't ES6 and mainly React use it
