### ISSUE TITLE
Babel docs still say .jsx, but deprecated now

### ISSUE THREAD

**Issue by alex-wilmer** [grigio/meteor-babel#17]
[Here it says you can still use .jsx, but I believe it is not supported anymore](https://babeljs.io/docs/using-babel/)

**Comment by alex-wilmer** [comment]
Err.. I guess it works again. It broke a bunch of my apps last week. Nevermind! =D

**Comment by jeffshaver** [comment]
@alex-wilmer it was changed to not support because of issue #10 but it was switched again to use a babel.json file if you didn't want jsx compiling which is on by default again because of pr #14

**Comment by alex-wilmer** [comment]
Ok great thanks for letting me know.
