### ISSUE TITLE
Meteor launch error

### ISSUE THREAD

**Issue by madshargreave** [grigio/meteor-babel#20]
I get the following error message when I run 'meteor'

While loading plugin `compile6to5` from package `grigio:babel`:
   native: Unexpected token /
   at Object.parse (native)
   at Package (packages/compile6to5/plugin/compile-6to5.js:54:1)
   at <runJavaScript-71>:83:4
   at <runJavaScript-71>:90:3

I tried removing the JSX extension from the babel.json file, but this doesnt work.

I use it in conjuction with the grove:react package

**Comment by jeffshaver** [comment]
I just added grove:react and threw some JSX into a project with no issues. Anything else that may be conflicting?

**Comment by grigio** [comment]
With grove:react no babel.json is needed.. Where did u put it? Do you use jsx extension in js files?

**Comment by madshargreave** [comment]
I want to us ES6 features, but does grove:react or babel handle the transpiling? Currently, all my JS files have JSX extension

**Comment by grigio** [comment]
it depends which react+meteor you use. With `grove:react` Babel transpiles the JSX. You can look at [TodoMVC example](https://github.com/grigio/todomvc-meteor-react).

**Comment by madshargreave** [comment]
I was modelling my initial application after that exact example, using the same packages, but I still get the error

**Comment by jeffshaver** [comment]
Just throwing it out there, but it is an issue with malformed jsx? I feel like that would make sense with the unexpected token?

**Comment by grigio** [comment]
yes `Unexpected token /` try to remove /*\* @jsx React.DOM */ ? (if you have it)

**Comment by madshargreave** [comment]
@jeffshaver I have listed every JSX file and found no errors, besides from the error message, it seem the error occurs inside the package.

@grigio I dont use  /*\* @jsx React.DOM */

**Comment by grigio** [comment]
https://github.com/grovelabs/meteor-react/issues/7#issuecomment-97168452
