### ISSUE TITLE
Allow for configuration on the package level

### ISSUE THREAD

**Issue by iameli** [grigio/meteor-babel#22]
Hi,

We have a few Meteor applications and would like to use ES6 in all of them. The easiest way to do this is to add `grigio:babel` to our `core` package that is shared among all of the apps.

Unfortunately that means we can't use a `babel.json` file -- we'd need one in the root directory of each application.

To be honest I'm not sure the best way to go about allowing this; not totally familiar with the compile-time Meteor process. (If I were I'd just send a PR). But it would be nice if I could have one `babel.json` file in our `core` package and all of the applications use that to compile. Thoughts?

Thanks!

**Comment by grigio** [comment]
In a such scenario probably the easiest way is to fork `grigio:babel` and change the hardcoded default values. If your PR to configure `grigio:babel` at package level doesn't break the configuration at application level I'd merge it.

**Comment by iameli** [comment]
Hmm. Maddening. fourseven/meteor-scss does something similar [here](https://github.com/fourseven/meteor-scss/blob/master/plugin/compile-scss.js#L39) but that works by looking at `compileStep.fullInputPath`, and by the time we're in the handler it's too late to configure the file extensions that we'll be watching.

Going to poke at this a bit more then probably file a ticket against Meteor.

**Comment by iameli** [comment]
I'ma close this -- Meteor will eventually be adding more compile-time package-level configuration, this will be easy enough to address then.
