### ISSUE TITLE
babel within a package does not compile from 6 to 5

### ISSUE THREAD

**Issue by minheq** [grigio/meteor-babel#25]
So when I try to create the class below within a package **package-name/lib/test.es6.js**

``` javascript
class Person {
    constructor(name) {
      this.name = name;
    }
}
```

include it in **package-name/package.js**

``` javascript
api.addFiles([
    'lib/test.es6.js'
], both);
```

I get an error:

```
While building package acam:core:
lib/test.es6.js:1:15: Unexpected reserved word
```

But when it is it exists outside, such as: **app/lib/test.es6.js** it will work properly. Is it the package's issue?

Also to mention, if i manually add the _griogio:babel_ package to the **app/packages** then have a package depend on _griogio:babel_ then I would have it working properly.

**Comment by bitomule** [comment]
You need to use a different file extension. Change your js to jsx. That worked for me.
