### ISSUE TITLE
Can't find variable: SYMBOL_ITERATOR

### ISSUE THREAD

**Issue by bitomule** [grigio/meteor-babel#26]
I've having a huge issue crashes on line 1768 of grigio_babel.js

This is the error:

```
O[SYMBOL_ITERATOR] = $.that;
```

**Comment by trusktr** [comment]
I've got the same error. It looks like this:

```
=> Your application has errors. Waiting for file change.
=> Modified -- restarting.
=> Errors prevented startup:

   While loading plugin `rocket:module` from package `rocket:module`:
   packages/grigio:babel/lib/core-js-no-number.js:1060:1: SYMBOL_ITERATOR is not defined
   at checkIter (packages/grigio:babel/lib/core-js-no-number.js:1060:1)
   at getCollection (packages/grigio:babel/lib/core-js-no-number.js:1089:1)
   at Object../$ (packages/grigio:babel/lib/core-js-no-number.js:1233:1)
   at s (packages/grigio:babel/lib/core-js-no-number.js:10:1)
   at packages/grigio:babel/lib/core-js-no-number.js:10:1
   at Object../src/es5 (packages/grigio:babel/lib/core-js-no-number.js:25:1)
   at s (packages/grigio:babel/lib/core-js-no-number.js:10:1)
   at e (packages/grigio:babel/lib/core-js-no-number.js:10:1)
   at hasOwn (packages/grigio:babel/lib/core-js-no-number.js:10:1)
   at hasOwn (packages/grigio:babel/lib/core-js-no-number.js:2233:1)
   at <runJavaScript-48>:2249:4
   at <runJavaScript-48>:2838:3
```

Is this some problem with the way `grigio:babel` is configured? Or maybe there's a bug that needs to be reported to Babel? I'm not sure!

**Comment by grigio** [comment]
can you explain the steps you did to get this error?

**Comment by trusktr** [comment]
@grigio I can't reproduce the error (I guess because my code base has changed). I'll just keep grigio:babel installed and if it happens I'll save it in a branch so you can try it out.

**Comment by trusktr** [comment]
I'm on 0.1.4 and still having this problem. As a temporary solution, I'm switched to MDG's `jsx` package (although I'm not using any JSX at all), which handles all the ES6 features I've been using.

**Comment by Eruant** [comment]
Same thing on iOS9
![screen shot 2015-09-14 at 13 44 41](https://cloud.githubusercontent.com/assets/1408374/9849874/cd09b474-5ae6-11e5-95ac-2274718ad1d8.png)

**Comment by grigio** [comment]
is this the same bug as #30 ? It seems there is a fix

**Comment by Eruant** [comment]
Look like it, can we merge the change? @nerdmed @grigio

**Comment by grigio** [comment]
if you confirm it works I'll merge a PR

**Comment by nerdmed** [comment]
Hi @Eruant and @grigio yes it should work well did not find any issue till know. Our App is up and running after a hot code reload on iOS9 - i have created a PR #38
