### ISSUE TITLE
underscore 1.0.2 native depedency

### ISSUE THREAD

**Issue by grigio** [grigio/meteor-babel#3]
Currently it seems that babel depends on a native dep so it need to be rebuilt on every change for every supported architecure.

Currently supported `osx-x64` and `linux-x64`

**Comment by grigio** [comment]
I've open #4

**Comment by boxxxie** [comment]
Maybe it would be good to switch out underscore for lodash

**Comment by grigio** [comment]
It isn't a my choice, but a babel dependency somewhere
