### ISSUE TITLE
Can't find variable: SYMBOL_ITERATOR on iOS 9 (beta) Safari & Cordova

### ISSUE THREAD

**Issue by ctaloi** [grigio/meteor-babel#30]
Hello,

I came across this today using the iOS 9 Beta (13A4293g) and thought you might want to know.  The error `Can't find variable: SYMBOL_ITERATOR` is thrown in the console and the Meteor app fails to come up.
- I can only duplicate using this beta version of iOS.
- I can duplicate using all browsers on iOS (Chrome, Safari and a Cordova built app).
- The error is only thrown when starting meteor using the --production flag (thus minifying) or connecting to a deployed app.

To get the console error you have to attach to the iOS device and then connect using the desktop Safari develop menu.

I can duplicate using the following:

```
meteor create foo
cd foo
meteor add grigio:babel
meteor run --production
```

The app loads fine on the desktop but fails on iOS.

**Comment by grigio** [comment]
Probably it is a dupl of #26 can you try if it happens also with the soon official MDG babel package? https://github.com/meteor/react-packages/tree/master/packages/babel-compiler

**Comment by nerdmed** [comment]
@ctaloi  for everyone not using the new MDG package here is a quick fix:

https://github.com/flowkey/meteor-babel
