### ISSUE TITLE
async await code not run

### ISSUE THREAD

**Issue by AChusuei** [grigio/meteor-babel#35]
In a file called `s3.es6`, I have a client side only piece of code that looks like this:

```
_.each(binaryStringChunks, async function (binaryStringChunk, index) {
    var fileChunkNumber = index + 1;
    var uploadFileChunkResults = await Meteor.promise('uploadFileChunk', file.type, file.name, path, binaryStringChunk, progressId, fileChunkNumber);
    console.log(uploadFileChunkResults);
    console.log('array index', index, 'size', chunk.length);
})
```

This does seem to compile, and I can actually see the transpiled code, alongside this original code when I load up my app in the browser:

```
_.each(binaryStringChunks, function callee$2$0(binaryStringChunk, index) {
    var fileChunkNumber, uploadFileChunkResults;
    return regeneratorRuntime.async(function callee$2$0$(context$3$0) {
        while (1) switch (context$3$0.prev = context$3$0.next) {
            case 0:
                fileChunkNumber = index + 1;
                context$3$0.next = 3;
                return regeneratorRuntime.awrap(Meteor.promise('uploadFileChunk', file.type, file.name, path, binaryStringChunk, progressId, fileChunkNumber));

            case 3:
                uploadFileChunkResults = context$3$0.sent;

                console.log(uploadFileChunkResults);
                console.log('array index', index, 'size', chunk.length);

            case 6:
            case 'end':
                return context$3$0.stop();
        }
    }, null, this);
});
```

When I debug the bowser though, the problem is that Meteor seems to be running the original code, and not the transpiled code, so when it hits the async function here, it doesn't seem to do anything. 

Is there something I need to do to get this to run the transpiled code. Like some sort of file rename? I'm not sure what I'm missing here

**Comment by benjamn** [comment]
Try turning off source maps in Chrome to see what's really happening, line by line?

**Comment by AChusuei** [comment]
Yeah, I JUST figured that part out ... for some reason i thought the source map was a meteor specific thing.

**Comment by AChusuei** [comment]
Never mind, I made a mistake in my code. Closing ...
