### ISSUE TITLE
package is breaking other NPM modules

### ISSUE THREAD

**Issue by dcsan** [grigio/meteor-babel#37]
I have a very weird error caused when adding this package, in that it breaks another NPM package 
even though that package doesn't use any es6 files.

any suggestions?

https://github.com/aichaos/rivescript-js/issues/39

this is a vanilla normal JS app I just added babel to in order to start using some es6 features, but it breaks the app immediately as above :?:

**Comment by grigio** [comment]
`grigio:babel`doesn't transpile non enabled files.. but weird things can happen.

**Comment by dcsan** [comment]
moved to the jsx preview from MDG and the problem went away...
