### ISSUE TITLE
BROKEN on iOS 9 Safari

### ISSUE THREAD

**Issue by ffxsam** [grigio/meteor-babel#39]
I've flagged the package as broken on Atmosphere.

https://forums.meteor.com/t/meteor-site-no-longer-works-on-ios-9-safari/9979

**Comment by grigio** [comment]
Maybe related to #38 did the previous version worked for you? Unfortunatly i dont have ios9 to test this issue

**Comment by ffxsam** [comment]
Great! That fixed it. I unflagged the package.

**Comment by ffxsam** [comment]
@grigio BTW, if you're on a Mac, you can download Xcode and run `/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app` to run the iOS 9 simulator.

**Comment by grigio** [comment]
no, I can't upgrade xcode now. Glad it fixed
