### ISSUE TITLE
core-js breaks matching Numbers

### ISSUE THREAD

**Issue by adrianpacala** [grigio/meteor-babel#5]
Because core-js [overrides Number constructor](https://github.com/zloirock/core-js/blob/master/src/es6.number.constructor.js), it's no longer possible to do `check(123, Number)`, as it throws:

```
W20150221-08:51:31.279(1)? (STDERR) Error: Match error: Expected Number
W20150221-08:51:31.279(1)? (STDERR)     at checkSubtree (packages/check/match.js:252:1)
W20150221-08:51:31.279(1)? (STDERR)     at check (packages/check/match.js:32:1)
```

One solution to this is to put `grigio:babel` before `meteor-platform` to make Meteor store the proper Number constructor in its [match package](https://github.com/meteor/meteor/blob/devel/packages/check/match.js#L141), but I think that's not an ideal solution.

**Comment by grigio** [comment]
Good to know

**Comment by boxxxie** [comment]
i have this issue too

**Comment by settinghead** [comment]
+1

**Comment by grigio** [comment]
If I enable core-js only on the the client "Generators functions" and "Sets" don't work anymore on the server

**Comment by settinghead** [comment]
For those who need a temporary solution:
Copy whatever package is causing trouble into the `package/` folder of your project, and add `grigio:babel` into its `package.js` as a dependency.

In my case the official `check` package stopped working, so I just copied the [entire package folder](https://github.com/meteor/meteor/tree/devel/packages/check) into my project and added the said dependency, which solved my problem.

**Comment by grigio** [comment]
@apacala AFAIK there is no hook to load something before `meteor-platform` or at least before `check` package (as @settinghead found as workaround )

**Comment by adrianpacala** [comment]
@grigio there is, just reorder them in `.meteor/packages`.

**Comment by grigio** [comment]
@apacala Ok, but it isn't something I can control via package api

**Comment by smowden** [comment]
fyi a workaround is also passing numbers with 

new Number(x)
check works fine then

**Comment by grigio** [comment]
@smowden :) but a meteor package shouldn't break Meteor behavior

**Comment by smowden** [comment]
no doubt, just sharing how I worked around this in the meantime in a small codebase that i recently started from scratch :)

**Comment by seeekr** [comment]
thanks for posting your workaround, @settinghead, works for me as well. Hoping for a proper fix soon! Looking forward to code in ES6 with Meteor!

**Comment by settinghead** [comment]
@grigio FYI: https://github.com/zloirock/core-js/issues/38#issuecomment-76114855

**Comment by jeffshaver** [comment]
@grigio why is this closed? The workaround that was mentioned first by @apacala works, but it would be ideal if this just worked. At this point is there any "sanctioned" work around. I read through the comments and agree that a package shouldn't break default meteor behavior, but for now, what solution should we use?

**Comment by grigio** [comment]
@jeffshaver This bug isn't closed. The [workaround](https://github.com/grigio/meteor-babel/blob/master/tests/basic_test.es6.js#L65) suggested is documented in the tests.

**Comment by zloirock** [comment]
Simplest way to fix - custom build core-js w/o wrapped `Number` constructor (octal & binary in `Number` constructor will not be available):

``` cmd
npm i -g grunt-cli
npm i core-js
cd node_modules/core-js && npm i
grunt build:es5,es6,es7,js,web --blacklist=es6.number.constructor --path=custom
```

But it's not correct way. `core-js` should be required before other modules.

**Comment by ljharb** [comment]
Because of cross-realm concerns, you should never be relying on `Number`, or `instanceof`, or the `constructor` property, anywhere in your JS. The only reliable way to determine if something is a non-primitive number is used by https://www.npmjs.com/package/is-number-object.

If you use this module instead of improperly relying on constructors, these issues with `core-js` and `es6-shim` will vanish.
