### ISSUE TITLE
error "no compatible build found"

### ISSUE THREAD

**Issue by boxxxie** [grigio/meteor-babel#6]
when i run meteor test-packages with your package i get this error

```
While checking for grigio:babel@0.0.1:
   error: No compatible build found
```

when i use other 6to5 packages i don't get this error

**Comment by grigio** [comment]
The current version is `grigio:babel@0.0.5` probably you installed it on a different platform. Try to run `meteor update`

**Comment by boxxxie** [comment]
i don't use a version number. this isn't obvious.
actually, i didn't even know i could use a version number in meteor.

**Comment by grigio** [comment]
I mean if you update your `grigio:babel` or run `meteor add grigio:babel` on a new project you shouldn't see that error
