### ISSUE TITLE
Unable to use classes in separate files

### ISSUE THREAD

**Issue by tomitrescak** [grigio/meteor-babel#9]
I have a following structure:

``` javascript
//file: /models/class1.jsx
class Foo {
}

//file: /models/class2.jsx
class Bar extends Foo {
}
```

I keep receiving `ReferenceError: Foo is not defined`

Any idea how to deal with this issue? Was using mquandalle:harmony till now and no issues there, but the package has gone to hell and babel looks more promising.

**Comment by tomitrescak** [comment]
I checked the build files and found out that babel generates classes as following:

``` javascript
var Foo = (function () { ...
```

That is, it is only local and not global.
Adding `export class ...` leads to uncompilable code.

``` javascript
var World = exports.World = (function () { ...
```

As a solution I needed to add the `met:exports` package, which is fine for now, but I would prefer if this would become part of the package.

**Comment by grigio** [comment]
Meteor doesn't support explicit dependency loading `export / import`. `mrt:exports` do not manage `import`. http://docs.meteor.com/full/structuringyourapp#fileloadorder

Probably the current best way to manage the classes is to put them in `lib/` (or nested `lib/`) and define them as `Item = class Item {...}`

**Comment by trusktr** [comment]
Just a guess, but I think that you can specify classes in separate packages and control load order. But I don't see why yours doesn't work considering that `/models/class2.jsx` should load after `/models/class1.jsx` since it is comes after in alphabetical order.

**Comment by tomitrescak** [comment]
@trusktr the problem is not the load order. Problem is that class is generated as "private" with `var Foo = (function () { ...` and as a result it is not accessible to the application.

**Comment by idmontie** [comment]
This is the same problem that [Meteor Harmony](https://github.com/mquandalle/meteor-harmony) has.

**Comment by grigio** [comment]
The root of this issue is in Meteor https://github.com/meteor/meteor/issues/4062#issuecomment-88254321

**Comment by trusktr** [comment]
I'm working on https://atmospherejs.com/rocket/module to make it easy to use ES6/AMD/CJS module formats in Meteor.

**Comment by grigio** [comment]
other approches are:
https://atmospherejs.com/universe/modules
https://github.com/jedwards1211/meteor-webpack-react
